#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst) // 最长前缀匹配
{	// 注意上面的注释表示地址是host 字节序
	// fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	
	rt_entry_t * ret_entry = NULL;
	rt_entry_t * pos, *q;

	list_for_each_entry_safe(pos, q, &rtable, list)
	{
		if((dst & pos->mask) == (pos->dest & pos->mask)) // match
		{
			if(ret_entry == NULL) // first match
			{
				ret_entry = pos;
			}
			else if (ret_entry->mask < pos->mask)
			{
				ret_entry = pos;
			}
			
		}
	}

	return ret_entry;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	// fprintf(stderr, "TODO: send ip packet.\n");
	struct iphdr *ip_head = packet_to_ip_hdr(packet);
	// struct icmphdr * icmp_head = (struct icmphdr *)(packet + ETHER_HDR_SIZE + IP_BASE_HDR_SIZE);
	rt_entry_t * rt_p = NULL;
	// 重新设置校验和
	ip_head->checksum = ip_checksum(ip_head); // 在 ip checksum中没有修改字节序，因此这里也就没改

	// 查找路由表里面的MAC地址
	rt_p = longest_prefix_match(ntohl(ip_head->daddr));
	
	if(rt_p == NULL) // not match
	{
		icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		free(packet); 
	}
	else // match
	{
		u32 gateway_addr = rt_p->gw;
		if(gateway_addr == 0) // 如果网关地址为0，说明下一跳就是目的地址
		{
			gateway_addr = ntohl(ip_head->daddr);
		}

		iface_send_packet_by_arp(rt_p->iface, gateway_addr, packet, len); // 这里只拿到了ip地址，还没有拿到mac地址，因此不能直接用iface send函数
	}
	
}
